name: 🚀 Deploy to QA website on push
on:
  push:
    branches:
      - master
      - develop

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2.3.2

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

      - name: 📦 Install Composer dependencies
        uses: MilesChou/composer-action/7.4/install@v7
        with:
          args: --no-dev --prefer-dist --optimize-autoloader --no-interaction --no-progress --no-suggest --no-scripts
          composer_options: --no-dev --prefer-dist --optimize-autoloader --no-interaction --no-progress --no-suggest --no-scripts
          composer_version: 2
          php_version: 7.4
          cache_dir: /tmp/composer-cache

      - name: 📂 Sync files
        uses: wangyucode/sftp-upload-action@v1.4.8
        with:
          host: ${{ secrets.ftp_server }}
          username: ${{ secrets.ftp_user }}
          password: ${{ secrets.ftp_password }}
          remoteDir: public_html/wp-content/plugins/sca-recipe
          exclude: '.git*,.DS_Store'
          forceUpload: true
          dryRun: false
          removeExtraFilesOnServer: true