name: 🚀 Deploy to QA website on push
on:
  push:
    branches:
      - main
      - develop

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2.3.2

      - name: 📂 Sync files
        uses: wangyucode/sftp-upload-action@v1.4.8
        with:
          host: ${{ secrets.ftp_server }}
          username: ${{ secrets.ftp_user }}
          password: ${{ secrets.ftp_password }}
          remoteDir: public_html/wp-content/plugins/sca-recipe
          exclude: '.git*,.DS_Store'
          forceUpload: true
          dryRun: false
          removeExtraFilesOnServer: true